# Generated by Django 2.0.13 on 2022-11-07 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subwayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subwayLineNumber', models.CharField(max_length=6)),
                ('getOffStationName', models.CharField(max_length=20)),
                ('trainNumber', models.CharField(max_length=4)),
                ('userNickname', models.CharField(max_length=20)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
